server:
  port: 8080
spring:
  application:
    name: msvc-zara
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  h2:
    console:
      enabled: true
      path: /h2-console
      show-sql: true
  datasource:
    url: jdbc:h2:mem:zara
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
