DROP TABLE IF EXISTS BRAND;
create table BRAND(
  ID int not null AUTO_INCREMENT,
  NAME varchar(100) not null,
  PRIMARY KEY ( ID )
);
DROP TABLE IF EXISTS PRICE;
create table PRICE(
  ID int not null AUTO_INCREMENT,
  BRAND_ID  int not null,
  START_DATE TIMESTAMP,
  END_DATE TIMESTAMP,
  PRICE_LIST int,
  PRODUCT_ID int,
  PRIORITY int,
  PRICE_AMOUNT DOUBLE,
  CURRENCY varchar(5),
  PRIMARY KEY ( ID ),
  CONSTRAINT fk_BRAND_ID_OFFER
  FOREIGN KEY (BRAND_ID)
  REFERENCES BRAND(ID)
);